### ISSUE TITLE
Pets are staying in place after logoff

### ISSUE THREAD

**Issue by tvgblade** [SmallCodee/SmallPets#17]
After I logoff the pet I have floating behind me becomes a floating head and doesn't disappear when I log off, i know have logged back in and the pet is floating there separate from me  and there are now 2 of them?
![image](https://user-images.githubusercontent.com/103161373/162635037-c1565447-84d8-4ca2-97ff-84f287ec012a.png)

**Comment by hannest03** [comment]
If you use protocollib this problem won't occur anymore

**Comment by tvgblade** [comment]
Protocollib is installed, is there anything else?

**Comment by hannest03** [comment]
Make sure that in the config useProtocollib is true, after that this error won't occur anymore.
You still have to remove the already spawned pets by hand with the kill command
