### ISSUE TITLE
Translation proposal

### ISSUE THREAD

**Issue by vgtom4** [SmallCodee/SmallPets#4]
Hello, I'm french and I suggest you that I translate your plugin "SmallPets" into French.
Would you agree ?

**Comment by hannest03** [comment]
Yes, that would be nice!

**Comment by vgtom4** [comment]
okay good.

**Comment by vgtom4** [comment]
i will start

**Comment by vgtom4** [comment]
To translate "pet", I put what?

Familier (familiar) / animal / pet / compagnon (companion) ?

**Comment by hannest03** [comment]
You could also just leave pet, at least that's what I did for italian, because animale domestico sounds strange in this case

**Comment by vgtom4** [comment]
yes ^^

**Comment by vgtom4** [comment]
I put "companion", it's good ?

**Comment by hannest03** [comment]
Yes

**Comment by vgtom4** [comment]
Here is

[translation fr.yml.zip](https://github.com/SmallCodee/SmallPets/files/5075473/translation.fr.yml.zip)

**Comment by hannest03** [comment]
Thanks

**Comment by vgtom4** [comment]
will you add more pets?

**Comment by hannest03** [comment]
yea after the next update
